### ISSUE TITLE
Forever while loop does not work with `true`

### ISSUE THREAD

**Issue by itssamuelrowe** [hypertool/kush#2]
The following program compiles without any issue:

```
void print(string value);

i32 main() {
   while 1 == 1 {
      print("hello, world!");
   }
   return 0;
}
```

However, this does not work:

```
void print(string value);

i32 main() {
   while true {
      print("hello, world!");
   }
   return 0;
}
```

The following error is printed by LLVM:
```
Branch condition is not 'i1' type!
  br i8 1, label %2, label %3
i8 1
LLVM ERROR: Broken module found, compilation aborted!
Aborted (core dumped)
```

It's seems like a type mismatch in the LLVM bytecode.

**Comment by ghost** [comment]
Seems like, for condition of `br` instruction, the LLVM IR does not take `true` as a value of type `i1`  but it does take the result of the comparison operation as a value of type `i1`. 

Where exactly is the keyword `true` parsed?

**Comment by itssamuelrowe** [comment]
Does `br` expect `i1` or `i8`? Currently `true` is represented by `i8`.

https://github.com/itssamuelrowe/kush/blob/3e4e4bc96e0bb488c09001efae82e3f2583d72f9/source/generator.c#L246

**Comment by ghost** [comment]
`br` expects a `i1`, yes. So `true` should be `1`. Or a more defensive approach would be to forcefully use bitcast instruction and convert everything you give to `br` instruction to `i1`. This would make your `while` and `if` statements to have implicit boolean results for conditions and expressions. Also is there a specific reason you need 8 bits to represent `true` or `false`?

**Comment by itssamuelrowe** [comment]
I don't think `i8` is a necessity. We can go with `i1`. Seems like the solution is a one-liner?

**Comment by itssamuelrowe** [comment]
This issue has been fixed: https://github.com/itssamuelrowe/kush/commit/371c8ab49ad0225e1b80430b4a85d1cb86a47cb1
